booking:
  property: Booking profile dev updated 2

spring:
  application:
    name: booking-microservice
  datasource:
   driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  testProp: Test property