booking:
  property: Product profile dev

spring:
  application:
    name: product-microservice
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/productdb

app:
  testProp: Test property updated v2